#!/usr/bin/env python3
"""
Battery Monitor - Switches TLP profile based on battery level
Runs every 2 minutes via systemd timer
"""

import subprocess
import sys
from pathlib import Path

CONFIG = "/etc/tlp.d/99-current-battery.conf"

# CPU frequency limits as percentages of max hardware frequency
CPU_FREQ_PERCENT = {
    "full": 100,      # 100% of max
    "balanced": 80,   # 80% of max
    "medium": 50,     # 50% of max
    "aggressive": 35  # 35% of max
}

# Battery thresholds and settings (cpu_freq_max calculated at runtime)
PROFILES = {
    "full": {
        "max_battery": 101,
        "min_battery": 81,
        "cpu_max": 100,
        "platform": "balanced",
        "disk_apm": "128 128",
        "sata": "med_power_with_dipm",
        "pcie": "default",
        "freq_percent": 100,
        "message": "FULL (100% CPU, {}GHz)"
    },
    "balanced": {
        "max_battery": 80,
        "min_battery": 51,
        "cpu_max": 80,
        "platform": "balanced",
        "disk_apm": "128 128",
        "sata": "med_power_with_dipm",
        "pcie": "default",
        "freq_percent": 80,
        "message": "BALANCED (80% CPU, {}GHz)"
    },
    "medium": {
        "max_battery": 50,
        "min_battery": 31,
        "cpu_max": 50,
        "platform": "balanced",
        "disk_apm": "128 128",
        "sata": "med_power_with_dipm",
        "pcie": "default",
        "freq_percent": 50,
        "message": "MEDIUM (50% CPU, {}GHz)"
    },
    "aggressive": {
        "max_battery": 30,
        "min_battery": 0,
        "cpu_max": 35,
        "platform": "low-power",
        "disk_apm": "64 64",
        "sata": "min_power",
        "pcie": "powersupersave",
        "freq_percent": 35,
        "message": "AGGRESSIVE (35% CPU, {}GHz)"
    }
}


def read_file(path):
    """Read content from a file, return empty string if not found."""
    try:
        return Path(path).read_text().strip()
    except (FileNotFoundError, PermissionError):
        return ""


def get_cpu_max_freq():
    """Get CPU max frequency in kHz from hardware."""
    try:
        for path in Path("/sys/devices/system/cpu/cpufreq").glob("policy*/cpuinfo_max_freq"):
            try:
                return int(read_file(path))
            except (ValueError, FileNotFoundError):
                continue
    except Exception:
        pass
    # Fallback: return 2.9 GHz if can't read
    return 2900000


def calc_freq(max_freq, percent):
    """Calculate frequency from percentage."""
    return int(max_freq * percent / 100)


def get_battery_level():
    """Get current battery percentage."""
    for path in Path("/sys/class/power_supply").glob("BAT*/capacity"):
        try:
            return int(read_file(path))
        except (ValueError, FileNotFoundError):
            continue
    return None


def is_on_ac_power():
    """Check if system is plugged in."""
    for path in Path("/sys/class/power_supply").glob("AC*/online"):
        try:
            return read_file(path) == "1"
        except FileNotFoundError:
            continue
    return False


def write_config(profile, freq_ghz):
    """Write TLP configuration file."""
    config_content = f"""# Auto-generated by battery-monitor.py
# Profile: {profile['message'].format(freq_ghz)}
CPU_SCALING_GOVERNOR_ON_BAT="powersave"
CPU_MAX_PERF_ON_BAT={profile['cpu_max']}
PLATFORM_PROFILE_ON_BAT="{profile['platform']}"
DISK_APM_LEVEL_ON_BAT="{profile['disk_apm']}"
SATA_LINKPWR_ON_BAT="{profile['sata']}"
PCIE_ASPM_ON_BAT="{profile['pcie']}"
WIFI_PWR_ON_BAT="on"
"""
    try:
        Path(CONFIG).write_text(config_content)
        return True
    except PermissionError:
        print(f"Error: Cannot write to {CONFIG}", file=sys.stderr)
        return False


def restart_tlp():
    """Restart TLP service to apply new settings."""
    try:
        subprocess.run(
            ["sudo", "systemctl", "restart", "tlp.service"],
            check=True,
            capture_output=True
        )
        return True
    except subprocess.CalledProcessError as e:
        print(f"Error restarting TLP: {e}", file=sys.stderr)
        return False


def set_cpu_frequency(freq_khz):
    """Set CPU max frequency for all cores."""
    try:
        # Find all CPU policies
        for policy_path in Path("/sys/devices/system/cpu/cpufreq").glob("policy*/scaling_max_freq"):
            try:
                policy_path.write_text(str(freq_khz))
            except (PermissionError, FileNotFoundError):
                continue
        return True
    except Exception as e:
        print(f"Error setting CPU frequency: {e}", file=sys.stderr)
        return False


def get_profile(battery):
    """Get the appropriate profile for current battery level."""
    for profile in PROFILES.values():
        if profile["min_battery"] <= battery < profile["max_battery"]:
            return profile
    return PROFILES["aggressive"]


def main():
    # Skip if on AC power
    if is_on_ac_power():
        print("On AC power - skipping")
        return 0

    # Get battery level
    battery = get_battery_level()
    if battery is None:
        print("Error: Could not read battery level", file=sys.stderr)
        return 1

    # Get CPU max frequency from hardware
    cpu_max_freq = get_cpu_max_freq()

    # Get appropriate profile
    profile = get_profile(battery)

    # Calculate actual frequency limit
    freq_khz = calc_freq(cpu_max_freq, profile["freq_percent"])
    freq_ghz = freq_khz / 1000000

    # Write new config
    if not write_config(profile, freq_ghz):
        return 1

    # Set CPU frequency limit directly
    if not set_cpu_frequency(freq_khz):
        print("Warning: Could not set CPU frequency", file=sys.stderr)

    # Restart TLP to apply settings
    if not restart_tlp():
        return 1

    msg = profile['message'].format(round(freq_ghz, 1))
    print(f"Battery {battery}% - {msg}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
